version: '3'

services:
  web:
    container_name: nginx
    build:
      context: deployment/docker/${APP}/nginx
      dockerfile: Dockerfile
    ports:
      - "2095:3000"
    volumes:
      - ./deployment/docker/${APP}/conf/${PROJECT}.conf:/etc/nginx/conf.d/${PROJECT}.conf
      - ./${PROJECT}:/var/www/html
    depends_on:
      - app

  app:
    container_name: php
    build:
      context: deployment/docker/${APP}/php
      dockerfile: php-fpm.docker
    volumes:
      - ./${PROJECT}:/var/www/html
    environment:
      - PHP_IDE_CONFIG=serverName=php
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
